# Syntax Support
set -g default-terminal "xterm"

# Clipboard Support
set-option -g default-command "reattach-to-user-namespace -l $SHELL"
set -s escape-time 0

# Vim Style Navigation
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Change Prefix
unbind C-b
set -g prefix C-a

# Highlight New Activity
setw -g monitor-activity on
set -g visual-activity on

# Renumber Windows After Closing
set -g renumber-windows on

# Increase Scrollback Lines
set -g history-limit 10000

# Switch to Last Pane
bind C-a last-pane

# Smart Pane Switching With Vim
bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"

# 'V' For Visual Mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
unbind -T copy-mode-vi Enter

# Resizing
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

# Clock
set-window-option -g clock-mode-style 12

# Status Bar
set -g status-bg colour8
set -g status-fg colour3
set -g status-left ''
set -g status-right ''
