#!/bin/bash

cd ~/.dotfiles

files=$(git ls-tree HEAD | cut -f2 | grep -v "install$")

for file in $files; do
  if [[ -L ~/$file ]]; then rm ~/$file; fi
  echo "Creating symlink to $file in home directory..."
  ln -s ~/.dotfiles/$file ~/$file
done
